### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by langj1** [markokoskinen2037/shipsinker2017#1]
Kaikilla koodissa käytetyillä metodeilla ja muuttujilla vaikuttaisi olevan kuvaavat ja loogiset nimet. Projektin loogiikka pakettiin kuuluva luokka GameField vaikuttaisi suorittavan gui:lle kuuluvia toimintoja esim. metodissa addShipToGui, sillä tulostaminen ja piirtäminen ei yleensä kuulu logiikkaan. GameField luokan attribuutti victory vaikuttaisi olevan turha, sillä sitä käytetään ainoastaan metodissa hasEnded, joka palauttaa attribuutin arvon, mutta metodia ei käytetä missään. Projekti ei sisällä hirveästi logiikka, joten testejä  ei ole paljon, mutta ne vaikuttaisivat kattavan kaiken oleellisen. Kokonaisuutena projekti näyttää hyvältä ja sillä on jo toimiva graafinen käyttöliittymä, mikä on mahtavaa. 

Ladattu: 5.2 20:30

**Comment by Samuel0c** [comment]
## Logiikka

Luokassa GameField metodissa addShipToGui for-loopissa ship1Cordinate voisi olla String Object-luokan sijaan ja "gui.getComponentByName(ship1Cordinate)" ei tarvinne toStringiä, sillä käsittelet koordinaatteja muutenkin String-muodossa.

Voisit myös harkita ajanottoa checkForShipEverySecond-metodissa. Yksinkertaisempi ratkaisu voisi olla tarkastaa vain alku- ja lopetusajan erotuksen jatkuvan ajan tarkastelun sijaan.

HighScores-luokassa updateBestPlayer-metodissa voisit mahdollisesti käyttää myös try-with-resources statementtia (https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) koodin siistimiseksi lyhyempään muotoon.

## GUI

Game-luokassa getComponentByName-metodissa tarkastellaan jokaista jButtonia. Tässä HashMap voisi olla tehokkaampi.

Sinulla on myös erilliset getterit jokaiselle painikkeelle, mikä pidentää koodia huomattavasti. Et vaikuta käyttävän niitä tällä hetkellä. Ellet aio käyttää niitä myöhemmin, ne voisi poistaa.

## Testit

Testisi ovat selkeitä ja keskittyvät hyvin vain yhden asian testaamiseen kerralla.

Kaiken kaikkiaan projektisi näyttää hyvältä ja laajennussuunnitelmasi vaikuttavat mielenkiintoisilta!

**Comment by markokoskinen2037** [comment]
Kiitokset molemmille katselmoijille kommenteista 👍
